include:
  - board: corneish_zen_left@2.0.0
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_right@2.0.0
  - board: corneish_zen_left@2.0.0
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_left@2.0.0_with_studio
  # - board: corneish_zen_v1_left
  # - board: corneish_zen_v1_right
